language: julia
sudo: false
os:
  - linux
julia:
  - 0.5
  - 0.6
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --compilecache=no -e 'Pkg.update();'
  - julia --compilecache=no --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("EcologicalNetwork"); Pkg.test("EcologicalNetwork"; coverage=true)'
after_success:
  - julia --compilecache=no -e 'cd(Pkg.dir("EcologicalNetwork")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia --compilecache=no -e 'cd(Pkg.dir("EcologicalNetwork")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia --compilecache=no -e 'Pkg.add("Documenter")'
  - julia --compilecache=no -e 'cd(Pkg.dir("EcologicalNetwork")); include(joinpath("docs", "make.jl"))'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6cf37ab29a014a2757c5
