language: julia

os:
  - linux

julia:
  - 0.7

env:
  - PYTHON=""

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --check-bounds=yes -e 'using Pkg;  Pkg.activate("."); Pkg.build("EcologicalNetworks"); Pkg.test("EcologicalNetworks"; coverage=true)'
 
after_success:
  - julia -e 'cd(Pkg.dir("EcologicalNetworks")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("EcologicalNetworks")); include(joinpath("docs", "make.jl"))'
