site_name:           ProbabilisticNetowrk.jl
repo_url:            https://github.com/PoisotLab/ProbabilisticNetowrk.jl
site_description:    Analysis of probabilistic ecological networks.
site_author:         Timoth√©e Poisot
theme:               readthedocs
markdown_extensions: [tables, fenced_code]
pages:
    - ['installation.md', 'Introduction', 'Installation']
    - ['introduction.md', 'Introduction', 'Introduction']
    - ['api.md', 'Full API reference']
