site_name:           ProbabilisticNetwork.jl
repo_url:            https://github.com/PoisotLab/ProbabilisticNetwork.jl
site_description:    Analysis of probabilistic ecological networks.
site_author:         Timoth√©e Poisot
theme:               readthedocs
markdown_extensions: [tables, fenced_code]
pages:
  - ['index.md', 'User guide']
  - ['install.md', 'User guide', 'Installation']
  - ['fsteps.md', 'User guide', 'First steps']
  - ['wrap.md', 'User guide', 'Wrappers']
  - ['api.md', 'Developer guide', 'API reference']
  - ['contr.md', 'Developer guide', 'Contribution guide']
