site_name: EcologicalNetwork.jl
repo_url: https://github.com/PoisotLab/EcologicalNetwork.jl
site_description: Analysis of ecological networks
site_author: Timoth√©e Poisot

theme: material

extra:
    logo: "images/logo.png"
    palette:
        primary: 'green'
        accent: 'teal'
    font:
        text: 'PT Sans'
        code: 'PT Mono'
    author:
        twitter: poisotlab
        github: poisotlab

extra_css:
    - assets/Documenters.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - assets/mathjaxhelper.js

markdown_extensions:
    - extra
    - tables
    - fenced_code
    - mdx_math
    - codehilite

docs_dir: 'build'

pages:
    - Home: index.md
    - "Use cases":
        - Nestedness: usecase/nestedness.md
    - Manual:
        - Types: man/types.md
        - Data: man/data.md
        - "Null models": man/nullmodels.md
        - Modularity: man/modularity.md
    - Library:
        - Public: lib/public.md
        - Internals: lib/internals.md
